### PR TITLE
fixed [Bug] Stop get resource list on goroutine when attach container…

### LINKED ISSUE #54: [Bug] Stop get resource list on goroutine when attach container .
Using goroutine to get resource list when init panels.
However, goroutine doesn't stop when attach container.

It need to stop goroutine before attach container.

```go
//  monitoring container status interval 5s
go func() {
	for {
		i.Update(func(g *gocui.Gui) error {
			return i.Refresh(g, v)
		})
		time.Sleep(5 * time.Second)
	}
}()

```

**reference article:**
https://blog.y-yuki.net/entry/2017/04/29/000000
https://qiita.com/castaneai/items/7815f3563b256ae9b18d

### PR DESCRIPTION
**Pull request by skanehira**
fixed #54

### CODE REVIEW

File: panel/containerPanel.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ type ContainerList struct {
 	Data       map[string]interface{}
 	filter     string
 	form       *Form
+	stop       chan int
```
Comment (d-kuro) [inline panel/containerPanel.go]: Use empty struct channel?
https://dave.cheney.net/2014/03/25/the-empty-struct

Comment (skanehira) [reply panel/containerPanel.go]: I'll use empty struct channel!
Thank you!
